service: testITDATA
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handlers/handlerHello.hello
    events:
      - httpApi:
          path: /hello
          method: get
  createToken:
    handler: src/handlers/handlerToken.createToken
    events:
      - httpApi:
          path: /create
          method: post
plugins:
  - serverless-plugin-typescript
  - serverless-offline
